### ISSUE TITLE
about _UNetSAGenerator 

### ISSUE THREAD

**Issue by chongagp** [hiroyasuakada/Self-Supervised-Learning-of-Domain-Invariant-Features-for-Depth-Estimation-WACV2022#1]
could you tell me  where did you use the _UNetSAGenerator in your Network architecture?

**Comment by hiroyasuakada** [comment]
Hi, this is from another project and you can simply ignore it.

**Comment by chongagp** [comment]
ok,but your training conditions are too difficult to achieve (8 A100 gpu), if I reduce the performance of the device (gtx3090), will the effect be seriously affected?

**Comment by hiroyasuakada** [comment]
I don’t know because I haven’t tried it.

But in general, you need to have a larger batch size for representation learning, which requires many gpus.
