### ISSUE TITLE
pre-training weight file of efficientnetb5

### ISSUE THREAD

**Issue by chongagp** [hiroyasuakada/Self-Supervised-Learning-of-Domain-Invariant-Features-for-Depth-Estimation-WACV2022#2]
Hello, could you please provide the pre-training weight file of efficientnetb5?

**Comment by hiroyasuakada** [comment]
I don't have that but you can download it like [this line](https://github.com/hiroyasuakada/Self-Supervised-Learning-of-Domain-Invariant-Features-for-Depth-Estimation-WACV2022/blob/bc00a7416b9aeec2421da783c844caf0b92c603d/model/network.py#L862-L863).

**Comment by chongagp** [comment]
thx a lot
